analytics:
  ua: ''
  gtag: 'G-7T27C539MP'
  gtm: ''
  ga_prod: 'G-7T27C539MP'
breadcrumbs:
  goal:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  indicator:
    - path: /
      label: general.home
    - path: /goals
      label: general.goals
  post:
    - path: /
      label: general.home
    - path: /news
      label: menu.updates
cookie_consent_form:
  enabled: false
country:
  name: Kenya
  adjective: Kenyan
create_goals:
  previous_next_links: false
  goals:
    - goal: 1
      content: >-
        
        Goal 1 calls for the eradication of poverty in all its forms. It envisions:
        
        -	shared prosperity
        
        -	a basic standard of living
        
        -	social protection benefits for people everywhere - including the poorest and most vulnerable
        
        It also seeks to ensure equal rights and access to economic and natural resources.
      heading: Goal 1 - No Poverty
      content_heading: End poverty in all its forms everywhere
    - goal: 2
      content: >-
        
        Goal 2 seeks to:
        
        -	end hunger and malnutrition
        
        -	ensure access to safe, nutritious, and sufficient food
        
        
        Achieving this goal will largely depend on:
        
        -	promoting sustainable production systems
        
        -	increasing investment in rural infrastructure and agricultural research and development
      heading: Goal 2 - Zero Hunger
      content_heading: End hunger, achieve food security and improved nutrition and promote sustainable agriculture
    - goal: 3
      content: >-
        
        Goal 3 aims to ensure the health and promote the well-being of everyone (of all ages) by:
        
        -	improving reproductive, maternal and child health
        
        -	ending epidemics of major contagious diseases
        
        -	reducing non-contagious diseases
        
        -	promoting mental health and well-being
        
        -	reducing behavioural and environmental health-risk factors
      heading: Goal 3 - Good Health and Well-Being
      content_heading: Ensure healthy lives and promote well-being for all at all ages
    - goal: 4
      content: >-
        
        Goal 4 seeks to:
        
        -	ensure access to fair, impartial and quality education through all stages of life
        
        -	increase the number of young people and adults who have the relevant skills for employment, decent jobs, and entrepreneurship
        
        -	eliminate gender and income disparities in access to education
      heading: Goal 4 - Quality Education
      content_heading: Ensure inclusive and equitable quality education and promote lifelong learning opportunities for all
    - goal: 5
      content: >-
        
        Goal 5 aims to achieve gender equality by:
        
        -	ending all forms of discrimination, violence and harmful practices against women and girls
        
        -	ensuring the full participation of women and equal opportunities for leadership at all levels of political and economic decision making
      heading: Goal 5 - Gender Equality
      content_heading: Achieve gender equality and empower all women and girls
    - goal: 6
      content: >-
      
        Goal 6 calls for ensuring universal access to:
        
        -	safe and affordable drinking water 
        
        -	sanitation and hygiene
        
        It also aims to:
        
        -	end defecation in the open
        
        -	improve water quality and water use efficiency 
        
        -	encourage sustainable abstractions and supply of freshwater
      heading: Goal 6 - Clean Water and Sanitation
      content_heading: Ensure availability and sustainable management of water and sanitation for all
    - goal: 7
      content: >-
      
        Goal 7 calls for:
        
        -	ensuring universal access to modern energy services
        
        -	improving energy efficiency
       
        -	increasing the share of renewable energy
        
        
        To accelerate the transition to an affordable, reliable and sustainable energy system that fulfils these demands countries need to:
        
        -	 facilitate access to clean energy research and technology 
        
        -	 promote investment in resource and energy-efficient solutions and related infrastructure
      heading: Goal 7 - Affordable and Clean Energy
      content_heading: Ensure access to affordable, reliable, sustainable and modern energy for all
    - goal: 8
      content: >-
      
        Goal 8 recognises the importance of sustained economic growth and high levels of economic productivity for:
        
        -	the creation of well-paid quality jobs 
        
        -	progressive improvement of resource efficiency in consumption and production
        
        
        It calls for: 
        
        -	opportunities for full employment and decent work for all 
        
        -	the eradication of forced labour, human trafficking and child labour
        
        -	the promotion of labour rights and safe and secure working environments
      heading: Goal 8 - Decent Work and Economic Growth
      content_heading: Promote sustained, inclusive and sustainable economic growth, full and productive employment and decent work for all
    - goal: 9
      content: >-
      
        Goal 9 calls for building resilient and sustainable infrastructure and promotes inclusive and sustainable industrialisation.
        It also recognises the importance of research and innovation for finding lasting solutions to social, economic, and environmental challenges.
      heading: Goal 9 - Industry, Innovation and Infrastructure
      content_heading: Build resilient infrastructure, promote inclusive and sustainable industrialization and foster innovation
    - goal: 10
      content: >-
      
        Goal 10 addresses inequalities within countries, including:
        
        -	income 
        
        -	age
        
        -	sex
        
        -	disability
        
        -	race
        
        -	ethnicity
        
        -	origin
        
        -	religion
        
        -	economic 
        
        -	any other status 
        
        
        It also addresses inequalities among countries (including those related to representation) and calls for the orderly and safe migration 
        and mobility of people.
      heading: Goal 10 - Reduced Inequalities
      content_heading: Reduce inequality within and among countries
    - goal: 11
      content: >-
        
        Goal 11 aims to renew and plan cities and other human settlements in a way that offers opportunities for all, whilst reducing resource use 
        and environmental impact. It calls for access for all to:
        
        -	basic services
        
        -	energy 
        
        -	housing
        
        -	transportation
        
        -	green public spaces
      heading: Goal 11 - Sustainable Cities and Communities
      content_heading: Make cities and human settlements inclusive, safe, resilient and sustainable
    - goal: 12
      content: >-
        
        Goal 12 calls for a comprehensive set of actions from businesses, policy-makers, researchers, and consumers to adapt to sustainable practices. 
        It envisions sustainable production and consumption based on advanced technological capacity, resource efficiency and reduced global waste.
      heading: Goal 12 - Responsible Consumption and Production
      content_heading: Ensure sustainable consumption and production patterns
    - goal: 13
      content: >-
        
        Goal 13 seeks to implement the commitment of the United Nations Framework Convention on Climate Change to achieving a climate-neutral world. 
        
        
        With a particular focus on supporting the least developed countries, it also aims to strengthen countries’ resilience and adaptive capacity to climate-related natural hazards and the resulting disasters.
      heading: Goal 13 - Climate Action
      content_heading: Take urgent action to combat climate change and its impacts
    - goal: 14
      content: >-
        
        Goal 14 aims to protect and ensure the sustainable use of oceans. This includes:
        
        -	the reduction of marine pollution
        
        -	the impacts of ocean acidification
        
        -	the ending of overfishing
        
        -	the conservation of marine and coastal areas and ecosystems
        
        
        Goal 14 has strong interdependencies with a broad range of other Sustainable Development Goals (SDGs), as oceans:
        
        -	sustain coastal economies and livelihoods
        
        -	contribute to food production
        
        -	remove carbon dioxide from the atmosphere
      heading: Goal 14 - Life Below Water
      content_heading: Conserve and sustainably use the oceans, seas and marine resources for sustainable development
    - goal: 15
      content: >-
        
        Goal 15 seeks to protect, restore, and promote the conservation and sustainable use of terrestrial, inland-water and mountain ecosystems by:
        
        -	managing forests sustainably
        
        -	halting deforestation
        
        -	combating desertification
        
        -	restoring degraded land and soil
        
        -	halting biodiversity loss 
        
        -	protecting threatened species
      heading: Goal 15 - Life on Land
      content_heading: Protect, restore and promote sustainable use of terrestrial ecosystems, sustainably manage forests, combat desertification, and halt and reverse land degradation and halt biodiversity loss
    - goal: 16
      content: >-
        
        Goal 16 calls for peaceful and inclusive societies based on:
        
        -	respect for human rights
        
        -	the protection of the most vulnerable
        
        -	the rule of law and good governance at all levels
        
        
        It also envisions transparent, effective, and accountable institutions.
      heading: Goal 16 - Peace, Justice and Strong Institutions
      content_heading: Promote peaceful and inclusive societies for sustainable development, provide access to justice for all and build effective, accountable and inclusive institutions at all levels
    - goal: 17
      content: >-
      
        Goal 17 calls for a global partnership for sustainable development. The goal highlights the importance of:
        
        -	global macroeconomic stability
        
        -	trade for developing countries 
        
        -	equitable rules for governing international trade 
        
        -	access to science, technology and innovation - particularly internet-based information and communications technology
        
        
        The goal also highlights the need to mobilise financial resources for developing countries from international sources (and through strengthened 
        domestic capacities) for revenue collection. 
      heading: Goal 17 - Partnerships for the Goals
      content_heading: Strengthen the means of implementation and revitalize the Global Partnership for Sustainable Development
create_indicators:
  previous_next_links: false
create_pages:
  - filename: ''
    folder: /goals
    layout: goals
    title: general.goals
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: status.reporting_status
  - filename: ''
    folder: /search
    layout: search
    title: search.search
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: 'UNIT_MEASURE'
  series: 'SERIES'
date_formats: []
disclaimer:
  phase: ''
  message: ''
  hidden: true
email_contacts:
  questions: sdg@knbs.or.ke
  suggestions: sdg@knbs.or.ke
  functional: sdg@knbs.or.ke
empty_metadata_placeholder: ''
empty_metadata_placeholder_sources: ''
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact-us
    translation_key: menu.contact_us
  - path: 'https://twitter.com/KNBStats?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor'
    translation_key: general.twitter
  - path: 'https://www.facebook.com/bureauofstatistics/'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  # - title: Lorem ipsum
  #   content: |
  #     Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi mollis
  #     cursus est sed dapibus.
  #  include: ''
  #  button_label: Read more
  #  button_link: 'https://example.com'
  #  rule_color: ''
  # - title: News
  #   content: |
  #     Check this page for news regarding the reporting of our statistics for global indicators and opportunities to contribute to measuring achievement of the sustainable development goals
  #   include: ''
  #   button_label: Read more
  #   button_link: 'https://sdg-kenya.github.io/Site/news/'
  #   rule_color: ''
frontpage_goals_grid:
  title: frontpage.heading_short
  description: frontpage.instructions_shorter
frontpage_introduction_banner:
  title: Kenya's Indicator Framework for Sustainable Development Goals
  description: frontpage.intro_body
goal_image_base: 'https://open-sdg.org/sdg-translations/assets/img/goals'
goal_image_extension: ''
goals_page:
  title: general.goals
  description: frontpage.instructions_shorter
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
graph_title_from_series: false
header_language_toggle: dropdown
hide_empty_metadata: true
hide_single_series: true
hide_single_unit: true
ignored_disaggregations: 
  - TIME_DETAIL
  - NATURE
  - Progress
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/indicator-config
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: /tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
  exclude_fields: []
  translated: false
indicator_tabs:
  tab_1: ''
  tab_2: ''
  tab_3: ''
  tab_4: ''
languages:
  - en
languages_public: []
logos: []
map_layers: []
map_options:
  disaggregation_controls: false
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: 'opensdg.mapColors.default'
menu:
  - path: /
    translation_key: general.home
    dropdown: []
  - path: /goals
    translation_key: general.goals
    dropdown: []
  - path: /reporting-status
    translation_key: menu.reporting_status
    dropdown: []
  - path: /publications/
    translation_key: menu.publications
    dropdown: []
  - path: /news
    translation_key: menu.updates
    dropdown: []
  - path: /faq
    translation_key: menu.faq
    dropdown: []
  - path: /about
    translation_key: menu.about
    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: global
    title: indicator.global_metadata
    description: indicator.global_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
meta_tags: []
news:
  category_links: false
observation_attributes: []
  # - field: 
  #   label: ''
  # - field: 
  #   label: ''
progress_status:
  status_heading: status.progress_status
  status_help: ''
  status_types:
  - value: not_available
    label: status.progress_not_available
    alt: status.progress_not_available
  - value: deterioration
    label: status.deterioration
    image: assets/img/progress/red-gauge.png
    alt: status.deterioration
  - value: limited_progress
    label: status.limited_progress
    image: assets/img/progress/orange-gauge.png
    alt: status.limited_progress
  - value: moderate_progress
    label: status.moderate_progress
    image: assets/img/progress/yellow-gauge.png
    alt: status.moderate_progress
  - value: substantial_progress
    label: status.substantial_progress
    image: assets/img/progress/green-gauge.png
    alt: status.substantial_progress
  - value: target_achieved
    label: status.target_achieved
    image: assets/img/progress/target-achieved-gauge.png
    alt: status.target_achieved
progressive_web_app: 
  enabled: true 
  name: Kenya SDG App
  short_name: Kenya SDG App
  precaching: true
proxy_indicators:
  label: ''
  description: ''
remote_data_prefix: 'https://sdg-kenya.github.io/Data/'
reporting_status:
  title: status.reporting_status
  description: status.description
  disaggregation_tabs: false
  status_types:
    - value: complete
      label: status.reported
      hide_on_goal_pages: false
    - value: notstarted
      label: status.no_data_available
      hide_on_goal_pages: false
    - value: notapplicable
      label: status.not_applicable
      hide_on_goal_pages: false
repository_url_data: 'https://github.com/SDG-Kenya/Data'
repository_url_site: 'https://github.com/SDG-Kenya/Site'
search_index_boost: []
search_index_extra_fields: []
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: /tree/develop/_data
  translation_link: ''
time_series_attributes:
  - field: COMMENT_TS
    label: footnote
  - field: DATA_LAST_UPDATE
    label: metadata_fields.national_data_update_url
use_new_config_forms: true
validate_indicator_config: false
validate_site_config: false
x_axis_label: ''
